# Generated by Django 3.2.3 on 2021-06-09 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rimg', models.ImageField(blank=True, upload_to='Rimages/')),
                ('ratings', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField()),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('local', models.CharField(max_length=100)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keshwapur', models.IntegerField()),
                ('Vidyanagar', models.IntegerField()),
                ('Akshaypark', models.IntegerField()),
                ('OldHubli', models.IntegerField()),
                ('Hosur', models.IntegerField()),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='Restos/')),
                ('item_price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('rest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('time', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.items')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodapp.userdata')),
            ],
        ),
    ]
